### ISSUE TITLE
Remove labstack/echo dependency

### ISSUE THREAD

**Issue by fako1024** [fako1024/httpc#27]
It seems that the package depends on `labstack/echo` just for the sake of parsing a specific HTTP error struct which can easily be provided locally.

Relevant link: https://github.com/els0r/goProbe/issues/111

DoD

- [x] Replace HTTP error struct with local type
- [x] Remove unnecessary dependency

**Comment by els0r** [comment]
Uh. Good find. Where did this pop up?

**Comment by fako1024** [comment]
> Uh. Good find. Where did this pop up?

Luck. Saw it when starting to peruse the dependencies in goProbe and was surprised to still see `labstack/echo` in there. :man_shrugging:
